input CreateOrderInput {
  productId: ID!
  quantity: Int!
  userId: ID!
}

type Mutation {
  createOrder(input: CreateOrderInput!): Order!
}

type Order {
  id: ID!
  orderedAt: String!
  product: Product!
  quantity: Int!
  status: OrderStatus!
  totalJpy: Int!
}

enum OrderStatus {
  CANCELLED
  DELIVERED
  PENDING
  SHIPPED
}

type Product {
  id: ID!
  name: String!
  priceJpy: Int!
}

type Query {
  user(id: ID!): User
  users(first: Int = 5): [User!]!
}

type User {
  avatarUrl: String!
  createdAt: String!
  email: String!
  gender: String @deprecated(reason: "Use pronouns instead.")
  id: ID!
  name: String!
  orders(status: OrderStatus): [Order!]!
  pronouns: String
}